[SS]
ss_url = # main url
ss_sheet_1 = # sheet name
ss_sheet_1_key_val = # value
ss_sheet_1_key_date = # date due date
ss_sheet_1_write =  # target col to write
ss_sheet_2 =
ss_sheet_1_key_val =
ss_sheet_1_key_date =
ss_sheet_2_write = 
ss_sheet_3 =
ss_sheet_1_key_val =
ss_sheet_1_key_date =
ss_sheet_3_write = 

[DIR]
dir_mut = # dir address on local
dir_key_col_1 = # use col to make a target key
dir_key_dtl_1 = # write details here
dir_key_cab_1 = 
dir_key_col_2 =
dir_key_dtl_2 =
dir_key_cab_2 = 
dir_key_col_3 =
dir_key_dtl_3 =
dir_key_cab_3 = 

[GEN]
gen_before = # before now days
gen_after = # after now days
